package Entidades;
// Generated 10/06/2015 16:33:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer codCliente;
     private EnderecoCliente enderecoCliente;
     private String nomeCliente;
     private String cpfCnpjCliente;
     private String emailUsuario;
     private String senhaUsuario;
     private Set vendas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(EnderecoCliente enderecoCliente, String nomeCliente, String cpfCnpjCliente, String emailUsuario, String senhaUsuario) {
        this.enderecoCliente = enderecoCliente;
        this.nomeCliente = nomeCliente;
        this.cpfCnpjCliente = cpfCnpjCliente;
        this.emailUsuario = emailUsuario;
        this.senhaUsuario = senhaUsuario;
    }
    public Cliente(EnderecoCliente enderecoCliente, String nomeCliente, String cpfCnpjCliente, String emailUsuario, String senhaUsuario, Set vendas) {
       this.enderecoCliente = enderecoCliente;
       this.nomeCliente = nomeCliente;
       this.cpfCnpjCliente = cpfCnpjCliente;
       this.emailUsuario = emailUsuario;
       this.senhaUsuario = senhaUsuario;
       this.vendas = vendas;
    }
   
    public Integer getCodCliente() {
        return this.codCliente;
    }
    
    public void setCodCliente(Integer codCliente) {
        this.codCliente = codCliente;
    }
    public EnderecoCliente getEnderecoCliente() {
        return this.enderecoCliente;
    }
    
    public void setEnderecoCliente(EnderecoCliente enderecoCliente) {
        this.enderecoCliente = enderecoCliente;
    }
    public String getNomeCliente() {
        return this.nomeCliente;
    }
    
    public void setNomeCliente(String nomeCliente) {
        this.nomeCliente = nomeCliente;
    }
    public String getCpfCnpjCliente() {
        return this.cpfCnpjCliente;
    }
    
    public void setCpfCnpjCliente(String cpfCnpjCliente) {
        this.cpfCnpjCliente = cpfCnpjCliente;
    }
    public String getEmailUsuario() {
        return this.emailUsuario;
    }
    
    public void setEmailUsuario(String emailUsuario) {
        this.emailUsuario = emailUsuario;
    }
    public String getSenhaUsuario() {
        return this.senhaUsuario;
    }
    
    public void setSenhaUsuario(String senhaUsuario) {
        this.senhaUsuario = senhaUsuario;
    }
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }




}


