package Entidades;
// Generated 10/06/2015 16:33:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EnderecoCliente generated by hbm2java
 */
public class EnderecoCliente  implements java.io.Serializable {


     private Integer codEndereco;
     private int cep;
     private String cidade;
     private String logradouro;
     private int numero;
     private String pais;
     private Set clientes = new HashSet(0);

    public EnderecoCliente() {
        
    }

	
    public EnderecoCliente(int cep, String cidade, String logradouro, int numero, String pais) {
        this.cep = cep;
        this.cidade = cidade;
        this.logradouro = logradouro;
        this.numero = numero;
        this.pais = pais;
    }
    public EnderecoCliente(int cep, String cidade, String logradouro, int numero, String pais, Set clientes) {
       this.cep = cep;
       this.cidade = cidade;
       this.logradouro = logradouro;
       this.numero = numero;
       this.pais = pais;
       this.clientes = clientes;
    }
   
    public Integer getCodEndereco() {
        return this.codEndereco;
    }
    
    public void setCodEndereco(Integer codEndereco) {
        this.codEndereco = codEndereco;
    }
    public int getCep() {
        return this.cep;
    }
    
    public void setCep(int cep) {
        this.cep = cep;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getLogradouro() {
        return this.logradouro;
    }
    
    public void setLogradouro(String logradouro) {
        this.logradouro = logradouro;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }




}


